### PR TITLE
Add db schema and connection

### PR DESCRIPTION
**Pull request by toddbontrager**

### CODE REVIEW

**Comment by LiaRowan** [comment]
Should the dates property on the trip schema be a string? Since it's a range of dates, it could be a tuple or an object with start and end properties.

**Comment by LiaRowan** [comment]
Also, what's the .gitkeep file that was added in your first commit? It looks empty.

**Comment by LiaRowan** [comment]
In the db config file, you're exporting db, but db is not defined.

**Comment by ryandhaase** [comment]
gitkeep just prevents an empty folder from being ignored by git... can remove the file is something has been added to the folder

**Pull request merged**
